### ISSUE TITLE
The given key 'LoaderBar' was not present in the dictionary

### ISSUE THREAD

**Issue by Andree12** [Mewnojs/PlantsVsZombies.NET#1]
```
 Unhandled exception. System.Collections.Generic.KeyNotFoundException: The given key 'LoaderBar' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Sexy.ResourceManager.StartLoadResources(String theResGroup) in C:\PlantsVsZombies.NET-master\PlantsVsZombies.NET-master\Lawn_Shared\Sexy\Resource\ResourceManager.cs:line 1160
   at Sexy.ResourceManager.TodLoadResources(String theGroup, Boolean doUnpackAtlasImages) in C:\PlantsVsZombies.NET-master\PlantsVsZombies.NET-master\Lawn_Shared\Sexy\Resource\ResourceManager.cs:line 1711
   at Sexy.TodLib.TodCommon.TodLoadResources(String theGroup) in C:\PlantsVsZombies.NET-master\PlantsVsZombies.NET-master\Lawn_Shared\Sexy.TodLib\Common\TodCommon.cs:line 582
   at Lawn.LawnApp.LoadingThreadProc() in C:\PlantsVsZombies.NET-master\PlantsVsZombies.NET-master\Lawn_Shared\Lawn\LawnApp.cs:line 246
   at Sexy.SexyAppBase.LoadingThreadProcStub() in C:\PlantsVsZombies.NET-master\PlantsVsZombies.NET-master\Lawn_Shared\Sexy\System\SexyAppBase.cs:line 251
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```
Any idea, what causes this error?

**Comment by Andree12** [comment]
Turns out, that this error doesn't appear when it is compiled with visual studio 2019, so if you guys get a error like this, you are compiling this with the wrong version of visual studio.

**Comment by WarlyTheCulinarian** [comment]
what version of visual studio 2019 did you use? mine gets this error even with visual studio 2019.
